#ifndef REGISTRATIONWIDGET_GLOBAL_H
#define REGISTRATIONWIDGET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(REGISTRATIONWIDGET_LIBRARY)
#  define REGISTRATIONWIDGET_EXPORT Q_DECL_EXPORT
#else
#  define REGISTRATIONWIDGET_EXPORT Q_DECL_IMPORT
#endif

#endif // REGISTRATIONWIDGET_GLOBAL_H
