#ifndef MAINPAGEWIDGET_GLOBAL_H
#define MAINPAGEWIDGET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MAINPAGEWIDGET_LIBRARY)
#  define MAINPAGEWIDGET_EXPORT Q_DECL_EXPORT
#else
#  define MAINPAGEWIDGET_EXPORT Q_DECL_IMPORT
#endif

#endif // MAINPAGEWIDGET_GLOBAL_H
